name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  shared_preferences: ^2.0.8
  firebase_messaging: ^14.7.10
  url_launcher: ^6.2.4
  animated_splash_screen: ^1.3.0
  fluttertoast: ^8.2.4
  mailer: ^6.1.0
  change_app_package_name: ^1.1.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.1
  build_runner: ^2.4.8

flutter:
  assets:
    - assets/
  uses-material-design: true